#!/bin/bash -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input critical hello/username || true
db_go

db_get hello/username
while ! getent passwd $RET > /dev/null 2>&1 || [ $(id -u "$RET") -eq 0 ]
#while  [ $(id -u "$RET") -eq 0 ]
do
  db_set hello/usernameagain ""
  db_input critical hello/usernameagain || true
  db_go
  db_get hello/usernameagain
done
db_set hello/username $RET

db_input critical hello/age || true
db_go

# Check their answer.
# db_get honey/username
# if getent passwd $RET > /dev/null 2>&1; then
#     # Poor misguided one..
#     echo "user exists"
# else
#     echo "user does not exists"
# fi


